# Generated by Django 4.2.7 on 2023-11-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('ManufacturerID', models.AutoField(primary_key=True, serialize=False)),
                ('ManufacturerName', models.CharField(max_length=255)),
                ('ContactInfo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QuantityInStock', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Specifications', models.TextField()),
                ('YearManufactured', models.DateField()),
                ('ManufacturerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.manufacturer')),
            ],
        ),
    ]
