# Generated by Django 4.2.7 on 2023-11-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
