# Generated by Django 4.2.7 on 2023-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_brand_id_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
