# Generated by Django 4.2.7 on 2023-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_customer_phone_number_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
