# Generated by Django 4.2.7 on 2023-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_motorbike_compression_ratio_motorbike_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=14),
        ),
    ]
