# Generated by Django 4.2.7 on 2023-11-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_customer_address_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ID',
        ),
        migrations.AddField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorbike',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
